// Lektion-14/runstore-client/src/pages/products/Product-List.tsx
import { useEffect, useState } from 'react';
import type { Product } from '../../models/Product';
import './products.css';
import ProductCard from '../../components/Product-Card';
import PageTitle from '../../components/ui/PageTitle';

function ProductList() {
  const [products, setProducts] = useState<Product[]>([]);

  useEffect(() => {
    // Anrop till vårt api...
    console.log('Calling useEffect');
    fetch('http://localhost:5001/products')
      .then((response) => response.json())
      .then((result) => setProducts(result));
  }, []);

  return (
    <main className='container'>
      <PageTitle text='Våra produkter' />
      <article id='product-list'>
        {products.map((product) => (
          <ProductCard product={product} />
        ))}
      </article>
    </main>
  );
}

export default ProductList;

// Lektion-16/angular-client/src/features/products/product-list/product-list.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { PageTitle } from "../../../shared/components/page-title/page-title";
import { Product } from '../../../shared/models/product';
import { ProductCard } from "../product-card/product-card";
import { ProductService } from '../../../core/services/product-service';

@Component({
  imports: [PageTitle, ProductCard],
  selector: 'app-product-list',
  styleUrl: './product-list.css',
  templateUrl: './product-list.html',
})
export class ProductList implements OnInit {
  private productService = inject(ProductService);
  protected pageTitle = signal("Våra produkter");
  protected products = signal<Product[]>([]);

  ngOnInit(): void {
    this.productService.getProducts().subscribe({
      next: response => this.products.set(response.data as Product[]),
      error: error => console.log(error)
    });
  }
}
